name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest # This ensures the environment has Xcode installed
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild build -project 'Job Tracker.xcodeproj' -scheme 'Job Tracker' -destination 'platform=iOS Simulator,name=iPhone 15'
